/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f411xx.h"
#include "drv_gpio.h"
#include "drv_i2c.h"

#define SLAVE_ADRESS	0x68
#define MY_ADDR 0x61;

GPIO_Handle_t button;
GPIO_Handle_t i2cPin;
I2C_Handle_t i2c1;

uint8_t buffer[32];
uint8_t cmd1 = 0x51;
uint8_t cmd2 = 0x52;
uint8_t lendata;
void delay() {
	for (int i = 0; i < 500000/2 ; i++);
}

void InitButton() {
	button.pGPIO = GPIOA;

	button.pinConfig.pinMode = GPIO_PINMODE_INPUT;
	button.pinConfig.outType = GPIO_OUTTYPE_PUPU;
	button.pinConfig.outSpeed = GPIO_OUTSPEED_HIGH;
	button.pinConfig.resPull = GPIO_RESPULL_NONE;
	button.pinConfig.altFunc = GPIO_ALTFUNC_0;

	GPIO_Init(&button);

}
void InitInterface_I2C1() {

	// Init gpio for scl and sda pin
	i2cPin.pGPIO = GPIOB;
	i2cPin.pinConfig.pinMode  = GPIO_PINMODE_ALT;
	i2cPin.pinConfig.outType  = GPIO_OUTTYPE_OD;
	i2cPin.pinConfig.outSpeed = GPIO_OUTSPEED_HIGH;
	i2cPin.pinConfig.resPull  =	GPIO_RESPULL_NONE;
	i2cPin.pinConfig.altFunc  = GPIO_ALTFUNC_4;

	i2cPin.pinConfig.pinNum   = GPIO_PINNUM_8;
	GPIO_Init(&i2cPin);

	i2cPin.pinConfig.pinNum   = GPIO_PINNUM_9;
	GPIO_Init(&i2cPin);


	i2c1.pI2C 				  = I2C1;

	i2c1.config.ACKControl	  = I2C_ACKCONTROL_ENABLE;
	i2c1.config.deviceAddress = MY_ADDR;
	i2c1.config.dutyCycleFM	  = I2C_DUTYCYCLEFM_2;
	i2c1.config.sclSpeed	  = I2C_SCLSPEED_SM;

	I2C_Init(&i2c1);


}
extern void initialise_monitor_handles(void);

int main(void)
{
	initialise_monitor_handles();

	InitButton();
	InitInterface_I2C1();
	while (1) {
		if (GPIO_ReadPin(GPIOA, GPIO_PINNUM_0)) {
			delay();

			I2C_MasterTransmit(&i2c1, SLAVE_ADRESS, &cmd1, 1, TRUE);
			I2C_MasterReceive(&i2c1, SLAVE_ADRESS, &lendata, 1, TRUE);

			I2C_MasterTransmit(&i2c1, SLAVE_ADRESS, &cmd2, 1, TRUE);
			I2C_MasterReceive(&i2c1, SLAVE_ADRESS, buffer, lendata, FALSE);
			buffer[lendata+1] = '\0';
			printf("Data : %s",buffer);
		}
	}
}
